name: rick_and_morty_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

    #router
  auto_route:
    9.0.0

    # DI (Get It)
  get_it: ^7.6.0
  injectable:
    ^2.1.2

    # BLoC
  flutter_bloc: ^8.1.5
  bloc: ^8.1.2

  # Remote
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.5
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.3

  # Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  shared_preferences: ^2.5.3

  path_provider: ^2.1.5
  path_provider_android: ^2.2.15

  # Generated
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2

  # UI Style package
  flutter_gen: ^5.3.2
  cupertino_icons:
    ^1.0.6

    # Utils
  dartz: ^0.10.1
  equatable: ^2.0.7
  gap: ^3.0.1
  intl: 0.19.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: 9.0.0
  flutter_gen_runner:
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
